//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcv.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Project_Images
    {
        public int Image_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string Image_Path { get; set; }
    
        public virtual tbl_Projects tbl_Projects { get; set; }
    }
}
