//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcv.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resume_Content
    {
        public int Content_ID { get; set; }
        public string Professional_Info { get; set; }
        public string Work_Experince { get; set; }
        public string Education { get; set; }
        public string Skills { get; set; }
        public string Languages { get; set; }
    }
}
