//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webcv.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public string User_Phone { get; set; }
        public string User_Job { get; set; }
        public string User_Fax { get; set; }
        public string User_Facebook_Url { get; set; }
        public string User_Twitter_Url { get; set; }
        public string User_GooglePlus_Url { get; set; }
        public string Home_Page_Text { get; set; }
    }
}
